capstone_areyoufree/apis/urls.py
from django.urls import path
from .views import EventViewSet, UserViewSet, CurrentUserView
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('events', EventViewSet, basename = 'events')
router.register('users', UserViewSet, basename = 'users')


urlpatterns = router.urls + [
    path('currentuser/', CurrentUserView.as_view()),
    
]

capstone_areyoufree/areyoufree_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apis/v1/', include('apis.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', TemplateView.as_view(template_name='calendar.html'), name='base')
]

capstone_areyoufree/users/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

capstone_areyoufree/apis/models.py
from django.db import models

# Create your models here.

capstone_areyoufree/events/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Event(models.Model):
    title = models.CharField(max_length=200)
    start_time = models.TimeField(auto_now = False, auto_now_add = False)
    end_time = models.TimeField(auto_now = False, auto_now_add = False)
    notes = models.TextField()
    event_auth = models.ManyToManyField(get_user_model(), related_name='events')
    date = models.DateField(blank = True, null = True)

    def __str__(self):
        return self.title

capstone_areyoufree/users/models.py
from datetime import date
import email
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, date_of_birth, password=None):
        # Create error messages for fields that are not filled when creating a new user
        if not email:
            raise ValueError("Must enter an EMAIL ADDRESS to create an account.")
        if not username:
            raise ValueError("Must enter a USERNAME to create an account.")
        if not first_name:
            raise ValueError("Must enter a FIRST NAME to create an account.")
        if not last_name:
            raise ValueError("Must enter a LAST NAME to create an account.")
        if not date_of_birth:
            raise ValueError("Must enter a DATE OF BIRTH to create an account.")

        user = self.model(
            email = self.normalize_email(email),
                #normalize_email converts all chars to lowercase
            username = username,
            first_name = first_name,
            last_name = last_name,
            date_of_birth = date_of_birth,
        )
        #Save user
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self, email, username, first_name, last_name, date_of_birth, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
            date_of_birth = date_of_birth,
        )
        # Set permissions for superuser
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        
        #Save user
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, verbose_name='email', unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField()

    # Required fields for custom user model
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name', 'date_of_birth']

    objects = UserManager()

    def __str__(self):
        return self.first_name

    # Required functions for custom user model
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

capstone_areyoufree/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'date_of_birth',
            'email',
            'username',
            'password1',
            'password2',
        ]

capstone_areyoufree/apis/views.py
from rest_framework import generics,  viewsets

from django.contrib.auth import get_user_model
from users.models import User
from events.models import Event
from .serializers import UserSerializer, EventSerializer

class CurrentUserView(generics.RetrieveAPIView):
    serializer_class = UserSerializer
    def get_object(self):
        return self.request.user

class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer

class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer

class CurentUserView(generics.RetrieveAPIView):
    serializer_class = UserSerializer
    def get_object(self):
        return self.request.user

capstone_areyoufree/events/views.py
from django.shortcuts import render

# Create your views here.

capstone_areyoufree/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import SignUpForm

class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

capstone_areyoufree/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Are You Free? - Calendar</title>
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css"/>
    <link rel="stylesheet" href="static/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Shadows+Into+Light+Two&display=swap" rel="stylesheet">

</head>
<body>
        {% csrf_token %}    

        {% if user.is_authenticated %}
        <div class="header">
            <h1>Hello, {{ user.first_name }}!</h1>
            <p><a href="{% url 'logout' %}">Logout</a></p>
        </div>  
        <div id="app">
            <!-- all VUE/JAVASCRIPT is in here! -->
            {% block content %}
            {% endblock %}
        </div>
        
        
        {% else %}
        <div class="header center">
            <p>Welcome to</p>
            <h1>Are You Free? Calendar!</h1>
            <p>Please <a href="{% url 'login' %}">login</a> or <a href="{% url 'users:signup' %}">sign up</a> to access your personal calendar</p>
        </div>
        {% endif %}
    
    <!-- Javascript/Vue links -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/dayjs@1.8.21/dayjs.min.js"></script>
    <script src="/static/app.js"></script>
</body>
</html>

capstone_areyoufree/templates/calendar.html
{% extends 'base.html' %}

{% block content %}


<div id="app">
    <div id="container">
        <div id="header">
            <div id="month-display"></div>
            <div>
                <button id="back-btn" @click="backPage">Previous Month</button>
                <button id="next-btn" @click="nextPage">Next Month</button>
            </div>
        </div>
        <div id="weekdays">
            <h3 v-for="weekday in weekdays">[[ weekday ]]</h3>
        </div>
        <div id="calendar"></div>
    </div>

    <div id="new-event-modal" class="center">
        <h2 class="center">New Event</h2>
        <label for="event-title-input">Event Title:</label><br>
        <input id="event-title-input"><br>
        <label for="start-time-input">Start Time:</label><br>
        <input id="start-time-input" type="time"><br>
        <label for="end-time-input">End Time:</label><br>
        <input id="end-time-input" type="time"><br>
        <label for="event-notes">Notes:</label><br>
        <input id="event-notes"><br>
        <hr>
        <button id="save-btn" @click="saveBtn">Save</button>
        <button id="cancel-btn" @click="closeModal">Cancel</button>
    </div>

    <div id="modal-back-drop"></div>

</div>


{% endblock %}   

capstone_areyoufree/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Are You Free? - Calendar</title>
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css"/>
    <link rel="stylesheet" href="static/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Shadows+Into+Light+Two&display=swap" rel="stylesheet">

</head>
<body>
        {% csrf_token %}    

        {% if user.is_authenticated %}
        <div class="header">
            <h1>Hello, {{ user.first_name }}!</h1>
            <p><a href="{% url 'logout' %}">Logout</a></p>
        </div>  
        <div id="app">
            {% block content %}
            {% endblock %}
        </div>
        
        
        {% else %}
        <div class="header center">
            <p>Welcome to</p>
            <h1>Are You Free? Calendar!</h1>
            <p>Please <a href="{% url 'login' %}">login</a> or <a href="{% url 'users:signup' %}">sign up</a> to access your personal calendar</p>
        </div>
        {% endif %}
    
    <!-- Javascript/Vue links -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/dayjs@1.8.21/dayjs.min.js"></script>
    <script src="/static/app.js"></script>
</body>
</html>